config/routes.rb
TenentManager::Application.routes.draw do

  resources :landlords, only: [:show, :new, :create]
  #match '/signup' => 'landlords#new'

begin
  resources :properties, only: [:new, :create, :show, :index] do
    resources :rental_apps, only: [:new, :create, :show, :index]
  end
end
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :address, :address2, :zipcode, :landlord_id

  has_many :rental_apps
  belongs_to :landlord

  validates :address, presence: true
  validates :zipcode, presence: true
  validates :landlord_id, presence: true


  def self.for(landlord)
    where(Landlord_id: landlord.id) unless landlord.nil?
  end

end

app/models/rental_app.rb
class RentalApp < ActiveRecord::Base
  attr_accessible  :email, :firstname, :lastname, :propertyaddress, :date_of_birth, :home_phone
  attr_accessible  :work_phone, :state_id_number, :state_issued, :current_employer_name
  attr_accessible  :current_employer_address, :current_employer_phone, :current_employer_length_of_employ
  attr_accessible  :current_employer_still_employed, :past_employer_name, :past_employer_address
  attr_accessible  :past_employer_phone, :past_employer_start_date, :past_employer_end_date
  attr_accessible  :employment_income, :other_income, :smoke, :eviction_history, :criminal_history
  attr_accessible  :bankruptcy, :comments

  belongs_to :property

  validates :email, format: { with: /@/ }, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :propertyaddress, presence:true
  validates :home_phone, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected

  def populate_properties_for_landlord
    landlord = Landlord.find(session[:landlord_id])
    @properties = Property.for(landlord).order 'address'
  end

  def ensure_list_for_current_user(list)
    if property.landlord != current_user
      render file: "#{Rails.root}/public/404", layout: false, status: :not_found and return
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
    @landlord = Landlord.find session[:landlord_id]
    populate_properties_for_landlord
    render 'empty' and return if @properties.empty?
  end

  def show
    @landlord = Landlord.find session[:landlord_id]
    populate_properties_for_landlord
    @prop = Property.find(params[:id])
  end

  def new
    @prop = Property.new
  end

  def create
    @prop = Property.create params[:property].merge(landlord_id: session[:landlord_id])
    if @prop.valid?
      redirect_to property_path(@prop)
      #redirect_to properties_path
    else
      render :new
    end

  end

end

app/controllers/rental_apps_controller.rb
class RentalAppsController < ApplicationController

    def new
      @prop = Property.find(params[:property_id])
      @rental_app = @prop.rental_apps.build
    end

    def index
      @property = Property.find(params[:property_id])
    end


    def create
      @prop = Property.find(params[:property_id])
      @rental_app = @prop.rental_apps.create(params[:rental_app])
      if @rental_app.save
        redirect_to property_rental_app_path(@prop, @rental_app)
      else
        render :new
      end

    end

    def show
      prop = Property.find(params[:property_id])
      #ensure_prop_visible prop
      @rental_app = RentalApp.find(params[:id])
      #ensure_rental_app_in_frig @rental_app, prop
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TenentManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/properties/_properties.html.erb
<div class='span-5 wishlist-sidebar-list'>
  <h2>Properties</h2>
  <ul>
    <% @properties.each do |property| %>
      <%= render partial: 'properties/property_name', locals: { property: property } %>
    <% end %>
    <li class='add'>
      <%= link_to "Add Property", '#' %>
    </li>
    <li class='new'>
      <%= form_for Property.new, url: properties_path, remote: true do |f| %>
        <%= f.text_field :address %>
        <%= f.text_field :zipcode %>

      <% end %>
    </li>
  </ul>
</div>

app/views/properties/_property_name.html.erb
<li>
  <a href="<%= property_path(property) %>">
    <%= property.address %>
    <span class='count'><%= property.rental_apps.count %></span>
  </a>
</li>

app/views/properties/empty.html.erb
<div class='empty container'>
  <div class='push-5 span-14'>
    <h1>You currently do not have any properties</h1>
    <div class='clear padded'>
      <%= link_to "+ Add a property", new_property_path, class: 'btn' %>
    </div>
  </div>
</div>

app/views/properties/index.html.erb
<div class='list-index-content container'>
  <%= render partial: 'properties' %>
  <div class='span-14 welcome'>
    <h1>Welcome!</h1>
    <h5> Go ahead, start adding properties</h5>
    <%= image_tag 'left-arrow.png' %>
  </div>
</div>

app/views/properties/new.html.erb
<div class='new-property-content container'>
  <div class='push-5 span-14'>
        <h1>New Property</h1>
        <h5>Go ahead, create a new property </h5>



        <% if @prop.errors.any? %>
        <div class='error'>
          <ul>
            <% @prop.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <%= form_for @prop do |f| %>
        <div>
          <%=	 f.label :address %>
          <%=     f.text_field :address %>
        </div>

        <div>
          <%=	 f.label :zipcode %>
          <%=     f.text_field :zipcode %>
        </div>

        <%= f.submit ('Register Property') %>
    <% end %>
    </div>
</div>

app/views/properties/show.html.erb
<H1> Your property has been submitted.</H1>
<H2> Thank you for using TenantManager!</H2>
<%= @prop.address %>
<%= @prop.zipcode %>
<%= @prop.landlord_id%>

app/views/rental_apps/_rentalapp_name.html.erb
<li>
  <a href="<%= property_rental_app_path(@property, rentalapp) %>">
    <%= rentalapp.firstname %>
    <%= rentalapp.lastname %>
    <%= rentalapp.updated_at %>
  </a>
</li>

app/views/rental_apps/_rentalapps.html.erb
<div class='span-5 wishlist-sidebar-list'>
  <h2>Rental Apps</h2>
  <ul>
    <% @property.rental_apps.each do |rentalapp| %>
        <%= render partial: 'rental_apps/rentalapp_name', locals: { rentalapp: rentalapp} %>
<% end %>

app/views/rental_apps/index.html.erb
<div class='list-index-content container'>
  <%= render partial: 'rental_apps/rentalapps' %>
  <div class='span-14 welcome'>
    <h1>Welcome!</h1>
    <h5> Go ahead, start adding properties</h5>
    <%= image_tag 'left-arrow.png' %>
  </div>
</div>

app/views/rental_apps/new.html.erb
<div class='new-rental_app-content container'>
  <div class='push-5 span-14'>
        <h1>New Rental Application</h1>
        <h5>Go ahead, fill out your application </h5>



        <% if @rental_app.errors.any? %>
        <div class='error'>
          <ul>
            <% @rental_app.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <%= form_for ([@prop, @rental_app]) do |f| %>
        <div>
          <%=	 f.label :firstname %>
          <%=     f.text_field :firstname %>
        </div>

        <div>
          <%=	 f.label :lastname %>
          <%=     f.text_field :lastname %>
        </div>

         <div>
          <%=	 f.label :email %>
          <%=     f.text_field :email %>
        </div>

        <div>
          <%=	 f.label :propertyaddress %>
          <%=     f.text_field :propertyaddress %>
        </div>

        <div>
          <%=	 f.label :home_phone %>
          <%=     f.text_field :home_phone %>
        </div>

        <div>
          <%=	 f.label :work_phone %>
          <%=     f.text_field :work_phone %>
        </div>

        <div>
          <%=	 f.label :date_of_birth %>
          <%=     f.text_field :date_of_birth %>
        </div>

        <div>
          <%=	 f.label :drivers_license_or_ID %>
          <%=     f.text_field :state_id_number %>
        </div>

        <div>
          <%=	 f.label :state_id_issued_in %>
          <%=     f.text_field :state_issued %>
        </div>

        <div>
          <%=	 f.label :current_employer_name %>
          <%=     f.text_field :current_employer_name %>
        </div>

        <div>
          <%=	 f.label :current_employer_address %>
          <%=     f.text_field :current_employer_address %>
        </div>

        <div>
          <%=	 f.label :current_employer_phone %>
          <%=     f.text_field :current_employer_phone %>
        </div>

        <div>
          <%=	 f.label :current_employer_length_of_employ %>
          <%=     f.text_field :current_employer_length_of_employ %>
        </div>

        <div>
          <%=	 f.label :current_employer_still_employed %>
          <%=     f.text_field :current_employer_still_employed %>
        </div>

        <div>
          <%=	 f.label :past_employer_name %>
          <%=     f.text_field :past_employer_name %>
        </div>

        <div>
          <%=	 f.label :past_employer_address %>
          <%=     f.text_field :past_employer_address %>
        </div>

        <div>
          <%=	 f.label :past_employer_phone %>
          <%=     f.text_field :past_employer_phone %>
        </div>

        <div>
          <%=	 f.label :past_employer_start_date %>
          <%=     f.text_field :past_employer_start_date %>
        </div>

        <div>
          <%=	 f.label :past_employer_end_date %>
          <%=     f.text_field :past_employer_end_date %>
        </div>
                         ----------------------------------------------------------
        <div>
          <%=	 f.label :employment_income %>
          <%=     f.text_field :employment_income %>
        </div>

        <div>
          <%=	 f.label :other_income %>
          <%=     f.text_field :other_income %>
        </div>

        <div>
          <%=	 f.label :do_you_smoke %>
          <%=     f.text_field :smoke %>
        </div>

        <div>
          <%=	 f.label :eviction_history %>
          <%=     f.text_field :eviction_history %>
        </div>

        <div>
          <%=	 f.label :criminal_history %>
          <%=     f.text_field :criminal_history %>
        </div>

        <div>
          <%=	 f.label :have_you_filed_bankruptcy %>
          <%=     f.text_field :bankruptcy %>
        </div>

        <div>
          <%=	 f.label :comments %>
          <%=     f.text_area :comments %>
        </div>




        <%= f.submit ('Sign Up') %>
    <% end %>
    </div>
</div>

app/views/rental_apps/show.html.erb
<H1> Your application has been submitted.</H1>
<H2> Thank you for using TenantManager!</H2>
<%= @rental_app.firstname %>
<%= @rental_app.lastname %>
<%= @rental_app.email %>
<%= @rental_app.propertyaddress %>